### PR TITLE
docker support

### PR DESCRIPTION
**Pull request by rbewley4**
This change allows you to run EPCC in a Docker container. Docker Compose
is used to automate all of the necessary steps, including running MySQL
in a separate container. MySQL data is stored in a Docker volume, so the
data persists even if you tear down the containers. The source code is
mounted directly in the application container to support live editing.

I moved the FullDatabase.sql file to its own directory (src/sql/init) so
that the mysql docker container could source it without sourcing the
other SQL files. I wish the docker image supported filters, or the
ability to select a specific file, but alas that is not the case.

The EPConfigFile class has been modified to support an override of the
config file path via environment variable EPCC_CONFIG_PATH. This was
needed so that the epcc docker container can use a different database
connection URI, and support live editing. Without this, the container
would have to make a copy of the source code and change the config file.

### CODE REVIEW

**Comment by EmperorArthur** [comment]
Hmm, I don't know anything about docker, but it looks fine.

How do you destroy the docker database when a DB change is made?  Also, are all the generated files already in `.gitignore`?

**Comment by rbewley4** [comment]
Docker does not generate any temporary files in the repository that would need to be ignored. Deleting the database volume is as simple as `docker volume rm epcharactercreator_epcc-db-data`.

After merging, we could delete the Vagrant code, as I think this is a superior method of running the application in a development environment.

**Comment by EmperorArthur** [comment]
Hmm, that command should probably be in the readme, but that's easy enough to do later.

Merging.

**Comment by EmperorArthur** [comment]
Added a little note in the readme, as well.

I'd appreciate it if you'd send a pull with the deleted Vagrant code.  I don't want to accidentally remove some of the Docker stuff, and don't really know what's what.

**Comment by rbewley4** [comment]
@EmperorArthur Pull request for deleting devbox (vagrant) code #100

**Pull request merged**
